[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = "off"
strip = false
lto = "off"
panic = "abort"
incremental = true
codegen-units = 256

[profile.release]
opt-level = "s"
debug = false
strip = true
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

[unstable]
build-std = ["panic_abort", "std"]
